name: Rehearsal TS Upgrade 
on:
  workflow_dispatch:
  push:
    branches: ['master']

jobs:
  test_action:
    name: Run Upgrade
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-path: './test'
